[package]
name = "sola"
version.workspace = true
edition.workspace = true

[dependencies]
sola-compositor = { path = "../sola-compositor" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
