use std::io;

use serde::Deserialize;

use crate::Message;

/// Trait implemented by all typed topic structs (generated by `define_topics!`).
pub trait Topic: Sized {
    /// The wire topic string, e.g. "shell::ShowSwitcher".
    const TOPIC: &'static str;

    /// Serialize this event's payload to bytes. Returns `None` for unit topics.
    fn to_payload(&self) -> Option<Vec<u8>>;

    /// Build a complete `Message` from this typed topic.
    fn to_message(&self) -> Message {
        match self.to_payload() {
            Some(payload) => Message::with_payload(Self::TOPIC, payload),
            None => Message::new(Self::TOPIC),
        }
    }
}

/// Decode a payload from a `Message` into the expected type.
pub fn decode_payload<T: for<'de> Deserialize<'de>>(event: &Message) -> io::Result<T> {
    let bytes = event
        .payload
        .as_ref()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "missing payload"))?;
    postcard::from_bytes(bytes).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))
}

/// Define typed topic structs within a category module.
///
/// # Example
/// ```ignore
/// define_topics! {
///     shell {
///         ShowSwitcher,
///         Apps(AppList),
///     }
/// }
/// // Generates: shell::ShowSwitcher, shell::Apps(AppList)
/// // Topic strings: "shell::ShowSwitcher", "shell::Apps"
/// ```
#[macro_export]
macro_rules! define_topics {
    (
        $category:ident {
            $( $variant:ident $( ( $payload:ty ) )? ),* $(,)?
        }
    ) => {
        pub mod $category {
            use super::*;

            $( $crate::_define_topic!($category, $variant $( ( $payload ) )? ); )*
        }
    };
}

/// Internal helper — generates a single topic struct + Topic impl.
#[macro_export]
#[doc(hidden)]
macro_rules! _define_topic {
    // Unit topic (no payload)
    ($category:ident, $variant:ident) => {
        #[derive(Debug, Clone, Copy)]
        pub struct $variant;

        impl $crate::topic::Topic for $variant {
            const TOPIC: &'static str = concat!(stringify!($category), "::", stringify!($variant));

            fn to_payload(&self) -> Option<Vec<u8>> {
                None
            }
        }
    };
    // Payload topic
    ($category:ident, $variant:ident ( $payload:ty )) => {
        #[derive(Debug, Clone)]
        pub struct $variant(pub $payload);

        impl $crate::topic::Topic for $variant {
            const TOPIC: &'static str = concat!(stringify!($category), "::", stringify!($variant));

            fn to_payload(&self) -> Option<Vec<u8>> {
                Some(postcard::to_allocvec(&self.0).expect("failed to serialize topic payload"))
            }
        }

        impl $variant {
            /// Decode the payload from a raw Message.
            pub fn decode(event: &$crate::Message) -> std::io::Result<$payload> {
                $crate::topic::decode_payload(event)
            }
        }
    };
}
