//! Theme — iced `Theme` with a sola-flavored extended palette.
//!
//! The kit hands every iced widget a `Theme::custom_with_fn`-built theme
//! whose `Extended` palette is generated by [`build_theme`]'s binding
//! closure instead of iced's default `Extended::generate`. That
//! generator is the kit's **binding layer** — it decides which of the
//! 10 hex atoms in [`hex`]
//! lands in each of iced's slots (`background.weaker`, `primary.strong`,
//! …). Component style fns then read from `theme.extended_palette()`
//! exactly like iced's own `button::primary` does. No global state, no
//! side struct.
//!
//! The legacy CEF kit ran the same atoms→bindings→component mapping in
//! CSS; here it's typed Rust against iced's existing palette vocabulary.
//! See `docs/vault/sola-kit.md` for the migration story.
//!
//! ## Mapping rationale
//!
//! Iced's `Background` has 8 tiers (weakest…base…strongest). We have
//! 4 background atoms (BG, BG_RAISED, BG_HOVER, BORDER). The mapping
//! biases toward exposing each atom on the slot iced apps reach for
//! first:
//!
//! | iced slot                | sola atom    | typical use                |
//! | ------------------------ | ------------ | -------------------------- |
//! | `background.base`        | `BG`         | window canvas              |
//! | `background.weakest`     | `BG`         | scrollable backgrounds     |
//! | `background.weaker`      | `BG_RAISED`  | sidebars, cards            |
//! | `background.weak`        | `BG_RAISED`  | (alias of weaker)          |
//! | `background.neutral`     | `BG_HOVER`   | between elevations         |
//! | `background.strong`      | `BG_HOVER`   | hover / selected rows      |
//! | `background.stronger`    | `BORDER`     | hairlines                  |
//! | `background.strongest`   | `BORDER`     | (alias of stronger)        |
//!
//! `primary.base` = `ACCENT`. `secondary.base` = `BORDER` with
//! `FG_MUTED` as the `text` pair, giving us muted-text-on-border for
//! deemphasized chrome. `success`/`warning`/`danger` map straight to
//! their atoms; iced auto-derives weak/strong tiers we don't need to
//! pin.

use iced::{Color, Theme};
use iced::theme::palette::{
    Background, Danger, Extended, Pair, Palette, Primary, Secondary, Success, Warning,
};

use sola_core::theme::Theme as BusTheme;

/// Theme name reported by `Theme::name()` — appears in `pick_list`
/// theme switchers and in the iced debug overlay.
pub const THEME_NAME: &str = "sola";

/// Canonical sola palette. Component style fns reach these through
/// `theme.extended_palette()`; direct `hex::*` references inside
/// component code are an escape hatch reserved for atoms iced's
/// vocabulary genuinely can't carry.
pub mod hex {
    pub const BG: &str = "#0d1117";
    pub const FG: &str = "#e6edf3";
    pub const ACCENT: &str = "#00d4ff";
    pub const SUCCESS: &str = "#3fb950";
    pub const WARNING: &str = "#d29922";
    pub const DANGER: &str = "#f85149";
    /// Muted variant of the foreground — secondary text (timestamps,
    /// deemphasized cells, captions).
    pub const FG_MUTED: &str = "#6e7681";
    /// Slightly lifted background — panels, sticky cards, sidebars.
    pub const BG_RAISED: &str = "#161b22";
    /// More lifted — hover / selected rows.
    pub const BG_HOVER: &str = "#1a2030";
    /// 1px hairline color.
    pub const BORDER: &str = "#2d333b";
}

/// Build the kit's iced theme from its compile-time default atoms.
/// Apps call this from their `theme(&self)` callback; the returned
/// `Theme::Custom` is cheap to clone (it wraps an `Arc<Custom>`).
pub fn default_theme() -> Theme {
    build_theme(&Atoms::default())
}

/// The binding layer — maps the kit's 10 colour atoms into iced's
/// `Extended` palette slots. This is the **single** place the
/// atom→slot layout lives; every theme the kit builds
/// ([`build_theme`], hence [`default_theme`] and [`theme_from_bus`])
/// routes through here. Component style fns read the resulting slots
/// via `theme.extended_palette()`; no component references `hex::*`
/// directly unless escape-hatching.
fn extended_from_atoms(a: &Atoms) -> Extended {
    let Atoms {
        bg, bg_raised, bg_hover, border, fg, fg_muted, accent, success, warning, danger,
    } = *a;
    Extended {
        background: Background {
            base: Pair::new(bg, fg),
            weakest: Pair::new(bg, fg),
            weaker: Pair::new(bg_raised, fg),
            weak: Pair::new(bg_raised, fg),
            neutral: Pair::new(bg_hover, fg),
            strong: Pair::new(bg_hover, fg),
            stronger: Pair::new(border, fg),
            strongest: Pair::new(border, fg),
        },
        // ACCENT — let iced derive weak/strong shades, no need to
        // hand-pin every tier when our palette is a single atom.
        primary: Primary::generate(accent, bg, fg),
        // Carries our muted-chrome story: secondary.base.color = BORDER,
        // .text = FG_MUTED. Style fns that want "deemphasized text on
        // a hairline-coloured surface" read from here.
        secondary: Secondary {
            base: Pair::new(border, fg_muted),
            weak: Pair::new(bg_hover, fg_muted),
            strong: Pair::new(border, fg),
        },
        success: Success::generate(success, bg, fg),
        warning: Warning::generate(warning, bg, fg),
        danger: Danger::generate(danger, bg, fg),
        is_dark: true,
    }
}

/// Build an iced `Theme` from an editable atom set — the one primitive
/// every other theme constructor composes. The base `Palette` carries
/// the headline atoms (so `theme.palette()` is sensible) while the
/// generator closure installs the full sola binding via
/// [`extended_from_atoms`].
pub fn build_theme(atoms: &Atoms) -> Theme {
    let a = *atoms;
    Theme::custom_with_fn(
        THEME_NAME.to_string(),
        Palette {
            background: a.bg,
            text: a.fg,
            primary: a.accent,
            success: a.success,
            warning: a.warning,
            danger: a.danger,
        },
        move |_| extended_from_atoms(&a),
    )
}

/// Parse `#rrggbb` into an iced `Color`. Panics on malformed input —
/// the inputs are compile-time constants in this crate, so the panic
/// is a self-check rather than a runtime concern.
pub fn parse(s: &str) -> Color {
    let s = s.trim_start_matches('#');
    assert_eq!(s.len(), 6, "expected #rrggbb, got {s:?}");
    let r = u8::from_str_radix(&s[0..2], 16).expect("rr") as f32 / 255.0;
    let g = u8::from_str_radix(&s[2..4], 16).expect("gg") as f32 / 255.0;
    let b = u8::from_str_radix(&s[4..6], 16).expect("bb") as f32 / 255.0;
    Color::from_rgb(r, g, b)
}

/// Try to parse `#rrggbb`, returning `None` on malformed input. Used
/// when ingesting bus theme atoms whose values arrive as untrusted
/// strings — a malformed swatch becomes a fallback rather than a
/// panic — and by the color picker's free-text hex field.
pub fn try_parse(s: &str) -> Option<Color> {
    let s = s.trim_start_matches('#');
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()? as f32 / 255.0;
    let g = u8::from_str_radix(&s[2..4], 16).ok()? as f32 / 255.0;
    let b = u8::from_str_radix(&s[4..6], 16).ok()? as f32 / 255.0;
    Some(Color::from_rgb(r, g, b))
}

/// Translate a bus theme (`sola_core::theme::Theme`) into the kit's
/// iced `Theme`. **Pure**: reads the colour atoms via
/// [`atoms_from_bus_theme`] and builds via [`build_theme`]; it does
/// *not* mutate the process font table. Pair it with an explicit
/// `fonts::install(fonts_from_bus_theme(bus))` (or use the
/// `sola_kit::apply_theme_update` helper, which does both):
///
/// ```ignore
/// Msg::Bus(msg) => {
///     if let Topic::Theme(bus) = &msg.topic {
///         self.theme = sola_kit::theme::theme_from_bus(bus);
///         sola_kit::fonts::install(sola_kit::theme::fonts_from_bus_theme(bus));
///     }
/// }
/// ```
///
/// Then return `self.theme.clone()` from `App::theme(&self)`.
pub fn theme_from_bus(bus: &BusTheme) -> Theme {
    build_theme(&atoms_from_bus_theme(bus))
}

/// Produce a bus theme (`sola_core::theme::Theme`) representing the
/// kit's compile-time default palette. Defined as the canonical
/// round-trip of the default atoms, so what the shell broadcasts at
/// boot reads back as exactly [`Atoms::default`] / [`default_theme`] —
/// no drift between the pre-replay frame and the seeded steady state.
pub fn to_bus_theme() -> BusTheme {
    bus_theme_from_atoms(&Atoms::default())
}


/// Editable atom set — every colour the iced kit's theme depends on,
/// held as `iced::Color` so the storybook can mutate one and rebuild.
///
/// This is the bridge between the kit's compile-time palette (the
/// `hex::*` constants) and the bus-side `BusTheme` schema. Both
/// directions go through here:
///
///   default constants → `Atoms::default`
///   `Atoms` → `iced::Theme` via [`build_theme`]
///   `Atoms` → `BusTheme`   via [`bus_theme_from_atoms`]
///
/// The storybook's editor mutates an `Atoms` value, then rebuilds and
/// re-emits both forms; other kit apps consume the bus form via
/// [`theme_from_bus`] and pick up the change on their next render.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Atoms {
    pub bg: Color,
    pub bg_raised: Color,
    pub bg_hover: Color,
    pub border: Color,
    pub fg: Color,
    pub fg_muted: Color,
    pub accent: Color,
    pub success: Color,
    pub warning: Color,
    pub danger: Color,
}

impl Default for Atoms {
    fn default() -> Self {
        Self {
            bg: parse(hex::BG),
            bg_raised: parse(hex::BG_RAISED),
            bg_hover: parse(hex::BG_HOVER),
            border: parse(hex::BORDER),
            fg: parse(hex::FG),
            fg_muted: parse(hex::FG_MUTED),
            accent: parse(hex::ACCENT),
            success: parse(hex::SUCCESS),
            warning: parse(hex::WARNING),
            danger: parse(hex::DANGER),
        }
    }
}

/// One row of the atom ⇄ bus-token mapping: which `Atoms` field a given
/// palette token drives, and the compile-time fallback used when the
/// token is missing or malformed.
///
/// **This is the single source of truth** consulted by both
/// [`atoms_from_bus_theme`] (read) and [`bus_theme_from_atoms`]
/// (write), so the read- and write-lists can never drift apart — the
/// drift that used to make `warning` silently fail to persist. To make
/// a new atom editable, add one row here.
struct AtomBinding {
    /// Bus palette token name.
    token: &'static str,
    /// Compile-time `hex::*` fallback when the token is absent/malformed.
    fallback: &'static str,
    /// Read the atom's value out of an `Atoms`.
    get: fn(&Atoms) -> Color,
    /// Write a value into the matching `Atoms` field.
    set: fn(&mut Atoms, Color),
}

const ATOM_BINDINGS: &[AtomBinding] = &[
    AtomBinding { token: "bg-primary",    fallback: hex::BG,        get: |a| a.bg,        set: |a, c| a.bg = c },
    AtomBinding { token: "bg-secondary",  fallback: hex::BG_RAISED, get: |a| a.bg_raised, set: |a, c| a.bg_raised = c },
    // Hover elevation reads the seed's real `bg-hover`, not `bg-tertiary`.
    AtomBinding { token: "bg-hover",      fallback: hex::BG_HOVER,  get: |a| a.bg_hover,  set: |a, c| a.bg_hover = c },
    AtomBinding { token: "border",        fallback: hex::BORDER,    get: |a| a.border,    set: |a, c| a.border = c },
    AtomBinding { token: "text-primary",  fallback: hex::FG,        get: |a| a.fg,        set: |a, c| a.fg = c },
    AtomBinding { token: "text-tertiary", fallback: hex::FG_MUTED,  get: |a| a.fg_muted,  set: |a, c| a.fg_muted = c },
    AtomBinding { token: "accent",        fallback: hex::ACCENT,    get: |a| a.accent,    set: |a, c| a.accent = c },
    AtomBinding { token: "success",       fallback: hex::SUCCESS,   get: |a| a.success,   set: |a, c| a.success = c },
    AtomBinding { token: "warning",       fallback: hex::WARNING,   get: |a| a.warning,   set: |a, c| a.warning = c },
    AtomBinding { token: "danger",        fallback: hex::DANGER,    get: |a| a.danger,    set: |a, c| a.danger = c },
];

/// Build a `BusTheme` from an editable atom set, writing every token in
/// [`ATOM_BINDINGS`]. Starts from the seed, so atoms the kit doesn't
/// model (`accent-dim`, `text-secondary`, sizes, radii, …) keep their
/// seed values; the kit's own tokens are overwritten — and inserted if
/// the seed somehow lacks them, preserving the write-list ⊇ read-list
/// invariant.
pub fn bus_theme_from_atoms(atoms: &Atoms) -> BusTheme {
    use sola_core::theme::{Token, TokenKind};
    let mut t = BusTheme::default();
    for binding in ATOM_BINDINGS {
        let value = color_to_hex((binding.get)(atoms));
        match t.palette.tokens.get_mut(binding.token) {
            Some(tok) => tok.value = value,
            None => {
                t.palette.tokens.insert(
                    binding.token.to_string(),
                    Token::new(TokenKind::Color, &value, &[]),
                );
            }
        }
    }
    t
}


/// Per-role family selection — what `Topic::Theme` carries on the wire
/// for the kit's font roles. Defaults match [`crate::fonts::Fonts::default`]
/// so a fresh storybook starts with SF Pro everywhere it offers a
/// pickable role.
#[derive(Debug, Clone)]
pub struct FontSelection {
    pub ui: String,
    pub ui_medium: String,
    pub display: String,
    pub chrome: String,
    pub mono: String,
}

impl Default for FontSelection {
    fn default() -> Self {
        Self {
            ui: "SF Pro".to_string(),
            ui_medium: "SF Pro".to_string(),
            display: "SF Pro".to_string(),
            chrome: "SF Pro".to_string(),
            mono: "JetBrains Mono".to_string(),
        }
    }
}

/// Merge font role selections into a `BusTheme`. Adds five
/// `FontFamily`-kind tokens — `font-ui`, `font-ui-medium`, `font-display`,
/// `font-chrome`, `font-mono` — so consumers can read them out via
/// [`fonts_from_bus_theme`] and reinstall the role table.
pub fn bus_theme_with_fonts(mut t: BusTheme, fonts: &FontSelection) -> BusTheme {
    use sola_core::theme::{Token, TokenKind};
    let writes = [
        ("font-ui",        fonts.ui.clone()),
        ("font-ui-medium", fonts.ui_medium.clone()),
        ("font-display",   fonts.display.clone()),
        ("font-chrome",    fonts.chrome.clone()),
        ("font-mono",      fonts.mono.clone()),
    ];
    for (name, value) in writes {
        t.palette.tokens.insert(
            name.to_string(),
            Token::new(TokenKind::FontFamily, &value, &["font-family"]),
        );
    }
    t
}

/// Build a complete `BusTheme` from an atoms + fonts pair. Convenience
/// over chaining [`bus_theme_from_atoms`] and [`bus_theme_with_fonts`].
pub fn bus_theme_from(atoms: &Atoms, fonts: &FontSelection) -> BusTheme {
    bus_theme_with_fonts(bus_theme_from_atoms(atoms), fonts)
}

/// Read the kit's font role tokens out of a `BusTheme` and build a
/// `crate::fonts::Fonts` table. Missing tokens fall back to the
/// process-wide default font selection.
pub fn fonts_from_bus_theme(bus: &BusTheme) -> crate::fonts::Fonts {
    let default = FontSelection::default();
    let read = |name: &str, fallback: &str| {
        bus.palette
            .tokens
            .get(name)
            .map(|t| t.value.clone())
            .unwrap_or_else(|| fallback.to_string())
    };
    let ui = read("font-ui", &default.ui);
    let ui_medium = read("font-ui-medium", &default.ui_medium);
    let display = read("font-display", &default.display);
    let chrome = read("font-chrome", &default.chrome);
    let mono = read("font-mono", &default.mono);
    crate::fonts::fonts_from_families(&ui, &ui_medium, &display, &chrome, &mono)
}


/// Read the colour atoms out of a `BusTheme` (the inverse of
/// [`bus_theme_from_atoms`]). Missing or malformed tokens fall back to
/// the kit's compile-time defaults, so a partial bus theme still
/// produces a usable `Atoms`. Table-driven via [`ATOM_BINDINGS`].
pub fn atoms_from_bus_theme(bus: &BusTheme) -> Atoms {
    let mut atoms = Atoms::default();
    for binding in ATOM_BINDINGS {
        let color = bus
            .palette
            .tokens
            .get(binding.token)
            .and_then(|t| try_parse(&t.value))
            .unwrap_or_else(|| parse(binding.fallback));
        (binding.set)(&mut atoms, color);
    }
    atoms
}

/// Read the font roles out of a `BusTheme` as a `FontSelection`
/// (string family names). Sibling to [`fonts_from_bus_theme`], which
/// returns the resolved `crate::fonts::Fonts` table.
pub fn font_selection_from_bus_theme(bus: &BusTheme) -> FontSelection {
    let default = FontSelection::default();
    let read = |name: &str, fallback: &str| {
        bus.palette
            .tokens
            .get(name)
            .map(|t| t.value.clone())
            .unwrap_or_else(|| fallback.to_string())
    };
    FontSelection {
        ui: read("font-ui", &default.ui),
        ui_medium: read("font-ui-medium", &default.ui_medium),
        display: read("font-display", &default.display),
        chrome: read("font-chrome", &default.chrome),
        mono: read("font-mono", &default.mono),
    }
}

/// Format an iced `Color` as a `#rrggbb` string (alpha dropped). The
/// inverse of [`parse`]; shared with the storybook's atom grid so it
/// doesn't reimplement the conversion.
pub fn color_to_hex(c: Color) -> String {
    let r = (c.r * 255.0).round().clamp(0.0, 255.0) as u8;
    let g = (c.g * 255.0).round().clamp(0.0, 255.0) as u8;
    let b = (c.b * 255.0).round().clamp(0.0, 255.0) as u8;
    format!("#{r:02x}{g:02x}{b:02x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    // A2: every editable atom — including `warning` — must survive a
    // round-trip through the bus theme. Regression guard for the
    // writelist that used to omit `warning`.
    #[test]
    fn all_atoms_round_trip_through_bus() {
        let atoms = Atoms {
            bg: parse("#010203"),
            bg_raised: parse("#040506"),
            bg_hover: parse("#070809"),
            border: parse("#0a0b0c"),
            fg: parse("#0d0e0f"),
            fg_muted: parse("#101112"),
            accent: parse("#131415"),
            success: parse("#161718"),
            warning: parse("#191a1b"),
            danger: parse("#1c1d1e"),
        };
        assert_eq!(atoms_from_bus_theme(&bus_theme_from_atoms(&atoms)), atoms);
    }

    // A1: the bus theme the kit broadcasts as its default must read back
    // as exactly the kit's default atoms, so the brief pre-replay frame
    // and the seeded steady state agree.
    #[test]
    fn default_bus_theme_reads_back_as_default_atoms() {
        assert_eq!(atoms_from_bus_theme(&to_bus_theme()), Atoms::default());
    }

    // A3: the hover elevation must come from the seed's real `bg-hover`
    // token (#1a2030), not `bg-tertiary` (#1c2129).
    #[test]
    fn hover_atom_reads_bg_hover_not_bg_tertiary() {
        let atoms = atoms_from_bus_theme(&BusTheme::default());
        assert_eq!(atoms.bg_hover, parse("#1a2030"));
        assert_ne!(atoms.bg_hover, parse("#1c2129"));
    }

    // Sub-decision (A4): the seed speaks the kit's font-role vocabulary,
    // not the old font-sans/font-mono placeholders.
    #[test]
    fn seed_speaks_font_role_vocabulary() {
        let tokens = &BusTheme::default().palette.tokens;
        for role in ["font-ui", "font-ui-medium", "font-display", "font-chrome", "font-mono"] {
            assert!(tokens.contains_key(role), "seed missing {role}");
        }
        assert!(!tokens.contains_key("font-sans"), "seed still carries font-sans");
    }

    // The seed's font roles must resolve to the kit's default font table.
    #[test]
    fn seed_fonts_resolve_to_default_table() {
        assert_eq!(
            fonts_from_bus_theme(&BusTheme::default()),
            crate::fonts::Fonts::default()
        );
    }

    // The writelist (atoms→bus) must cover every token the readlist
    // (bus→atoms) consumes, so no editable atom can silently fail to
    // persist. Trivially true while both share ATOM_BINDINGS — this
    // guards against a future split.
    #[test]
    fn writelist_covers_readlist() {
        let written = bus_theme_from_atoms(&Atoms::default());
        for binding in ATOM_BINDINGS {
            assert!(
                written.palette.tokens.contains_key(binding.token),
                "atom token {} is read but never written",
                binding.token
            );
        }
    }
}
