//! Theme — iced `Theme` with a sola-flavored extended palette.
//!
//! The kit hands every iced widget a `Theme::custom_with_fn`-built theme
//! whose `Extended` palette is generated by [`sola_extended`] instead of
//! iced's default `Extended::generate`. That generator is the kit's
//! **binding layer** — it decides which of the 10 hex atoms in [`hex`]
//! lands in each of iced's slots (`background.weaker`, `primary.strong`,
//! …). Component style fns then read from `theme.extended_palette()`
//! exactly like iced's own `button::primary` does. No global state, no
//! side struct.
//!
//! The legacy CEF kit ran the same atoms→bindings→component mapping in
//! CSS; here it's typed Rust against iced's existing palette vocabulary.
//! See `docs/vault/sola-kit.md` for the migration story.
//!
//! ## Mapping rationale
//!
//! Iced's `Background` has 8 tiers (weakest…base…strongest). We have
//! 4 background atoms (BG, BG_RAISED, BG_HOVER, BORDER). The mapping
//! biases toward exposing each atom on the slot iced apps reach for
//! first:
//!
//! | iced slot                | sola atom    | typical use                |
//! | ------------------------ | ------------ | -------------------------- |
//! | `background.base`        | `BG`         | window canvas              |
//! | `background.weakest`     | `BG`         | scrollable backgrounds     |
//! | `background.weaker`      | `BG_RAISED`  | sidebars, cards            |
//! | `background.weak`        | `BG_RAISED`  | (alias of weaker)          |
//! | `background.neutral`     | `BG_HOVER`   | between elevations         |
//! | `background.strong`      | `BG_HOVER`   | hover / selected rows      |
//! | `background.stronger`    | `BORDER`     | hairlines                  |
//! | `background.strongest`   | `BORDER`     | (alias of stronger)        |
//!
//! `primary.base` = `ACCENT`. `secondary.base` = `BORDER` with
//! `FG_MUTED` as the `text` pair, giving us muted-text-on-border for
//! deemphasized chrome. `success`/`warning`/`danger` map straight to
//! their atoms; iced auto-derives weak/strong tiers we don't need to
//! pin.

use iced::{Color, Theme};
use iced::theme::palette::{
    Background, Danger, Extended, Pair, Palette, Primary, Secondary, Success, Warning,
};

/// Theme name reported by `Theme::name()` — appears in `pick_list`
/// theme switchers and in the iced debug overlay.
pub const THEME_NAME: &str = "sola";

/// Canonical sola palette. Component style fns reach these through
/// `theme.extended_palette()`; direct `hex::*` references inside
/// component code are an escape hatch reserved for atoms iced's
/// vocabulary genuinely can't carry.
pub mod hex {
    pub const BG: &str = "#0d1117";
    pub const FG: &str = "#c9d1d9";
    pub const ACCENT: &str = "#58a6ff";
    pub const SUCCESS: &str = "#3fb950";
    pub const WARNING: &str = "#d29922";
    pub const DANGER: &str = "#f85149";
    /// Muted variant of the foreground — secondary text (timestamps,
    /// deemphasized cells, captions).
    pub const FG_MUTED: &str = "#6e7681";
    /// Slightly lifted background — panels, sticky cards, sidebars.
    pub const BG_RAISED: &str = "#161b22";
    /// More lifted — hover / selected rows.
    pub const BG_HOVER: &str = "#21262d";
    /// 1px hairline color.
    pub const BORDER: &str = "#30363d";
}

/// Build the kit's iced theme. Apps call this from their `theme(&self)`
/// callback; the returned `Theme::Custom` is cheap to clone (it wraps
/// an `Arc<Custom>`).
pub fn default_theme() -> Theme {
    Theme::custom_with_fn(
        THEME_NAME.to_string(),
        Palette {
            background: parse(hex::BG),
            text: parse(hex::FG),
            primary: parse(hex::ACCENT),
            success: parse(hex::SUCCESS),
            warning: parse(hex::WARNING),
            danger: parse(hex::DANGER),
        },
        sola_extended,
    )
}

/// The binding layer — maps sola hex atoms into iced's `Extended`
/// palette slots. Component style fns read through these slots; no
/// component should reference `hex::*` directly unless escape-hatching.
pub fn sola_extended(palette: Palette) -> Extended {
    let bg = parse(hex::BG);
    let bg_raised = parse(hex::BG_RAISED);
    let bg_hover = parse(hex::BG_HOVER);
    let border = parse(hex::BORDER);
    let fg = parse(hex::FG);
    let fg_muted = parse(hex::FG_MUTED);

    Extended {
        background: Background {
            base: Pair::new(bg, fg),
            weakest: Pair::new(bg, fg),
            weaker: Pair::new(bg_raised, fg),
            weak: Pair::new(bg_raised, fg),
            neutral: Pair::new(bg_hover, fg),
            strong: Pair::new(bg_hover, fg),
            stronger: Pair::new(border, fg),
            strongest: Pair::new(border, fg),
        },
        // ACCENT — let iced derive weak/strong shades, no need to
        // hand-pin every tier when our palette is a single atom.
        primary: Primary::generate(palette.primary, bg, fg),
        // Carries our muted-chrome story: secondary.base.color = BORDER,
        // .text = FG_MUTED. Style fns that want "deemphasized text on
        // a hairline-coloured surface" read from here.
        secondary: Secondary {
            base: Pair::new(border, fg_muted),
            weak: Pair::new(bg_hover, fg_muted),
            strong: Pair::new(border, fg),
        },
        success: Success::generate(palette.success, bg, fg),
        warning: Warning::generate(palette.warning, bg, fg),
        danger: Danger::generate(palette.danger, bg, fg),
        is_dark: true,
    }
}

/// Parse `#rrggbb` into an iced `Color`. Panics on malformed input —
/// the inputs are compile-time constants in this crate, so the panic
/// is a self-check rather than a runtime concern.
pub fn parse(s: &str) -> Color {
    let s = s.trim_start_matches('#');
    assert_eq!(s.len(), 6, "expected #rrggbb, got {s:?}");
    let r = u8::from_str_radix(&s[0..2], 16).expect("rr") as f32 / 255.0;
    let g = u8::from_str_radix(&s[2..4], 16).expect("gg") as f32 / 255.0;
    let b = u8::from_str_radix(&s[4..6], 16).expect("bb") as f32 / 255.0;
    Color::from_rgb(r, g, b)
}
