//! Theme — iced `Theme` with a sola-flavored extended palette.
//!
//! The kit hands every iced widget a `Theme::custom_with_fn`-built theme
//! whose `Extended` palette is generated by [`sola_extended`] instead of
//! iced's default `Extended::generate`. That generator is the kit's
//! **binding layer** — it decides which of the 10 hex atoms in [`hex`]
//! lands in each of iced's slots (`background.weaker`, `primary.strong`,
//! …). Component style fns then read from `theme.extended_palette()`
//! exactly like iced's own `button::primary` does. No global state, no
//! side struct.
//!
//! The legacy CEF kit ran the same atoms→bindings→component mapping in
//! CSS; here it's typed Rust against iced's existing palette vocabulary.
//! See `docs/vault/sola-kit.md` for the migration story.
//!
//! ## Mapping rationale
//!
//! Iced's `Background` has 8 tiers (weakest…base…strongest). We have
//! 4 background atoms (BG, BG_RAISED, BG_HOVER, BORDER). The mapping
//! biases toward exposing each atom on the slot iced apps reach for
//! first:
//!
//! | iced slot                | sola atom    | typical use                |
//! | ------------------------ | ------------ | -------------------------- |
//! | `background.base`        | `BG`         | window canvas              |
//! | `background.weakest`     | `BG`         | scrollable backgrounds     |
//! | `background.weaker`      | `BG_RAISED`  | sidebars, cards            |
//! | `background.weak`        | `BG_RAISED`  | (alias of weaker)          |
//! | `background.neutral`     | `BG_HOVER`   | between elevations         |
//! | `background.strong`      | `BG_HOVER`   | hover / selected rows      |
//! | `background.stronger`    | `BORDER`     | hairlines                  |
//! | `background.strongest`   | `BORDER`     | (alias of stronger)        |
//!
//! `primary.base` = `ACCENT`. `secondary.base` = `BORDER` with
//! `FG_MUTED` as the `text` pair, giving us muted-text-on-border for
//! deemphasized chrome. `success`/`warning`/`danger` map straight to
//! their atoms; iced auto-derives weak/strong tiers we don't need to
//! pin.

use iced::{Color, Theme};
use iced::theme::palette::{
    Background, Danger, Extended, Pair, Palette, Primary, Secondary, Success, Warning,
};

use sola_core::theme::Theme as BusTheme;

/// Theme name reported by `Theme::name()` — appears in `pick_list`
/// theme switchers and in the iced debug overlay.
pub const THEME_NAME: &str = "sola";

/// Canonical sola palette. Component style fns reach these through
/// `theme.extended_palette()`; direct `hex::*` references inside
/// component code are an escape hatch reserved for atoms iced's
/// vocabulary genuinely can't carry.
pub mod hex {
    pub const BG: &str = "#0d1117";
    pub const FG: &str = "#c9d1d9";
    pub const ACCENT: &str = "#58a6ff";
    pub const SUCCESS: &str = "#3fb950";
    pub const WARNING: &str = "#d29922";
    pub const DANGER: &str = "#f85149";
    /// Muted variant of the foreground — secondary text (timestamps,
    /// deemphasized cells, captions).
    pub const FG_MUTED: &str = "#6e7681";
    /// Slightly lifted background — panels, sticky cards, sidebars.
    pub const BG_RAISED: &str = "#161b22";
    /// More lifted — hover / selected rows.
    pub const BG_HOVER: &str = "#21262d";
    /// 1px hairline color.
    pub const BORDER: &str = "#30363d";
}

/// Build the kit's iced theme. Apps call this from their `theme(&self)`
/// callback; the returned `Theme::Custom` is cheap to clone (it wraps
/// an `Arc<Custom>`).
pub fn default_theme() -> Theme {
    Theme::custom_with_fn(
        THEME_NAME.to_string(),
        Palette {
            background: parse(hex::BG),
            text: parse(hex::FG),
            primary: parse(hex::ACCENT),
            success: parse(hex::SUCCESS),
            warning: parse(hex::WARNING),
            danger: parse(hex::DANGER),
        },
        sola_extended,
    )
}

/// The binding layer — maps sola hex atoms into iced's `Extended`
/// palette slots. Component style fns read through these slots; no
/// component should reference `hex::*` directly unless escape-hatching.
pub fn sola_extended(palette: Palette) -> Extended {
    let bg = parse(hex::BG);
    let bg_raised = parse(hex::BG_RAISED);
    let bg_hover = parse(hex::BG_HOVER);
    let border = parse(hex::BORDER);
    let fg = parse(hex::FG);
    let fg_muted = parse(hex::FG_MUTED);

    Extended {
        background: Background {
            base: Pair::new(bg, fg),
            weakest: Pair::new(bg, fg),
            weaker: Pair::new(bg_raised, fg),
            weak: Pair::new(bg_raised, fg),
            neutral: Pair::new(bg_hover, fg),
            strong: Pair::new(bg_hover, fg),
            stronger: Pair::new(border, fg),
            strongest: Pair::new(border, fg),
        },
        // ACCENT — let iced derive weak/strong shades, no need to
        // hand-pin every tier when our palette is a single atom.
        primary: Primary::generate(palette.primary, bg, fg),
        // Carries our muted-chrome story: secondary.base.color = BORDER,
        // .text = FG_MUTED. Style fns that want "deemphasized text on
        // a hairline-coloured surface" read from here.
        secondary: Secondary {
            base: Pair::new(border, fg_muted),
            weak: Pair::new(bg_hover, fg_muted),
            strong: Pair::new(border, fg),
        },
        success: Success::generate(palette.success, bg, fg),
        warning: Warning::generate(palette.warning, bg, fg),
        danger: Danger::generate(palette.danger, bg, fg),
        is_dark: true,
    }
}

/// Parse `#rrggbb` into an iced `Color`. Panics on malformed input —
/// the inputs are compile-time constants in this crate, so the panic
/// is a self-check rather than a runtime concern.
pub fn parse(s: &str) -> Color {
    let s = s.trim_start_matches('#');
    assert_eq!(s.len(), 6, "expected #rrggbb, got {s:?}");
    let r = u8::from_str_radix(&s[0..2], 16).expect("rr") as f32 / 255.0;
    let g = u8::from_str_radix(&s[2..4], 16).expect("gg") as f32 / 255.0;
    let b = u8::from_str_radix(&s[4..6], 16).expect("bb") as f32 / 255.0;
    Color::from_rgb(r, g, b)
}

/// Try to parse `#rrggbb`, returning `None` on malformed input. Used
/// when ingesting bus theme atoms whose values arrive as untrusted
/// strings — a malformed swatch becomes a fallback rather than a
/// panic.
fn try_parse(s: &str) -> Option<Color> {
    let s = s.trim_start_matches('#');
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()? as f32 / 255.0;
    let g = u8::from_str_radix(&s[2..4], 16).ok()? as f32 / 255.0;
    let b = u8::from_str_radix(&s[4..6], 16).ok()? as f32 / 255.0;
    Some(Color::from_rgb(r, g, b))
}

/// Translate a bus theme (`sola_core::theme::Theme`) into the kit's
/// iced theme. Atom names follow the v1 palette catalog seeded by
/// `sola_core::theme::Palette::seed` — `bg-primary` / `bg-secondary`
/// / `bg-tertiary` / `border` / `text-primary` / `text-tertiary` /
/// `accent` / `success` / `danger`. Missing or malformed atoms fall
/// back to the kit's compile-time defaults so a partial bus theme
/// still produces a usable iced theme.
///
/// Wire this into an app's update fn:
///
/// ```ignore
/// Msg::BusMessage(msg) => {
///     if let Topic::Theme(bus_theme) = &msg.topic {
///         self.theme = sola_kit::theme::from_bus_theme(bus_theme);
///     }
/// }
/// ```
///
/// Then return `self.theme.clone()` from `App::theme(&self)`. iced
/// re-renders on the next frame and the new palette flows through
/// every component style fn automatically.
pub fn from_bus_theme(bus: &BusTheme) -> Theme {
    let lookup = |name: &str, fallback: &str| -> Color {
        bus.palette
            .tokens
            .get(name)
            .and_then(|t| try_parse(&t.value))
            .unwrap_or_else(|| parse(fallback))
    };

    let bg = lookup("bg-primary", hex::BG);
    let bg_raised = lookup("bg-secondary", hex::BG_RAISED);
    let bg_hover = lookup("bg-tertiary", hex::BG_HOVER);
    let border = lookup("border", hex::BORDER);
    let fg = lookup("text-primary", hex::FG);
    let fg_muted = lookup("text-tertiary", hex::FG_MUTED);
    let accent = lookup("accent", hex::ACCENT);
    let success = lookup("success", hex::SUCCESS);
    let warning = lookup("warning", hex::WARNING);
    let danger = lookup("danger", hex::DANGER);

    Theme::custom_with_fn(
        THEME_NAME.to_string(),
        Palette { background: bg, text: fg, primary: accent, success, warning, danger },
        move |palette| Extended {
            background: Background {
                base: Pair::new(bg, fg),
                weakest: Pair::new(bg, fg),
                weaker: Pair::new(bg_raised, fg),
                weak: Pair::new(bg_raised, fg),
                neutral: Pair::new(bg_hover, fg),
                strong: Pair::new(bg_hover, fg),
                stronger: Pair::new(border, fg),
                strongest: Pair::new(border, fg),
            },
            primary: Primary::generate(palette.primary, bg, fg),
            secondary: Secondary {
                base: Pair::new(border, fg_muted),
                weak: Pair::new(bg_hover, fg_muted),
                strong: Pair::new(border, fg),
            },
            success: Success::generate(palette.success, bg, fg),
            warning: Warning::generate(palette.warning, bg, fg),
            danger: Danger::generate(palette.danger, bg, fg),
            is_dark: true,
        },
    )
}

/// Produce a bus theme (`sola_core::theme::Theme`) representing the kit's
/// compile-time default palette.
///
/// # Design note
/// The inverse of `from_bus_theme` would need to reverse-engineer named token
/// values from an iced `Theme`'s `Extended` palette — a lossy operation because
/// iced derives many colours from a few atoms. Rather than propagate a lossy
/// approximation onto the bus, this function returns a canned `BusTheme::default()`
/// (seeded with the v1 atom catalog via `Palette::seed`) that matches exactly
/// what `default_theme()` reads back. If the shell later lets users edit themes,
/// the real bus value should come from the theme editor, not from this function.
pub fn to_bus_theme() -> BusTheme {
    BusTheme::default()
}


/// Editable atom set — every colour the iced kit's theme depends on,
/// held as `iced::Color` so the storybook can mutate one and rebuild.
///
/// This is the bridge between the kit's compile-time palette (the
/// `hex::*` constants) and the bus-side `BusTheme` schema. Both
/// directions go through here:
///
///   default constants → `Atoms::default`
///   `Atoms` → `iced::Theme` via [`iced_theme_from_atoms`]
///   `Atoms` → `BusTheme`   via [`bus_theme_from_atoms`]
///
/// The storybook's editor mutates an `Atoms` value, then rebuilds and
/// re-emits both forms; other kit apps consume the bus form via
/// [`from_bus_theme`] and pick up the change on their next render.
#[derive(Debug, Clone, Copy)]
pub struct Atoms {
    pub bg: Color,
    pub bg_raised: Color,
    pub bg_hover: Color,
    pub border: Color,
    pub fg: Color,
    pub fg_muted: Color,
    pub accent: Color,
    pub success: Color,
    pub warning: Color,
    pub danger: Color,
}

impl Default for Atoms {
    fn default() -> Self {
        Self {
            bg: parse(hex::BG),
            bg_raised: parse(hex::BG_RAISED),
            bg_hover: parse(hex::BG_HOVER),
            border: parse(hex::BORDER),
            fg: parse(hex::FG),
            fg_muted: parse(hex::FG_MUTED),
            accent: parse(hex::ACCENT),
            success: parse(hex::SUCCESS),
            warning: parse(hex::WARNING),
            danger: parse(hex::DANGER),
        }
    }
}

/// Build an iced `Theme` from an editable atom set. Same shape as
/// [`from_bus_theme`] — only the source of the colours differs.
pub fn iced_theme_from_atoms(atoms: &Atoms) -> Theme {
    let Atoms {
        bg, bg_raised, bg_hover, border, fg, fg_muted, accent, success, warning, danger,
    } = *atoms;
    Theme::custom_with_fn(
        THEME_NAME.to_string(),
        Palette { background: bg, text: fg, primary: accent, success, warning, danger },
        move |palette| Extended {
            background: Background {
                base: Pair::new(bg, fg),
                weakest: Pair::new(bg, fg),
                weaker: Pair::new(bg_raised, fg),
                weak: Pair::new(bg_raised, fg),
                neutral: Pair::new(bg_hover, fg),
                strong: Pair::new(bg_hover, fg),
                stronger: Pair::new(border, fg),
                strongest: Pair::new(border, fg),
            },
            primary: Primary::generate(palette.primary, bg, fg),
            secondary: Secondary {
                base: Pair::new(border, fg_muted),
                weak: Pair::new(bg_hover, fg_muted),
                strong: Pair::new(border, fg),
            },
            success: Success::generate(palette.success, bg, fg),
            warning: Warning::generate(palette.warning, bg, fg),
            danger: Danger::generate(palette.danger, bg, fg),
            is_dark: true,
        },
    )
}

/// Build a `BusTheme` from an editable atom set, overwriting only the
/// token values [`from_bus_theme`] actually reads back. Unknown atoms
/// (e.g. `accent-dim`, `text-secondary`) keep their seed values — the
/// editor doesn't need to model atoms iced doesn't expose.
pub fn bus_theme_from_atoms(atoms: &Atoms) -> BusTheme {
    let mut t = BusTheme::default();
    for (name, value) in [
        ("bg-primary",   color_to_hex(atoms.bg)),
        ("bg-secondary", color_to_hex(atoms.bg_raised)),
        ("bg-tertiary",  color_to_hex(atoms.bg_hover)),
        ("border",       color_to_hex(atoms.border)),
        ("text-primary", color_to_hex(atoms.fg)),
        ("text-tertiary", color_to_hex(atoms.fg_muted)),
        ("accent",       color_to_hex(atoms.accent)),
        ("success",      color_to_hex(atoms.success)),
        ("danger",       color_to_hex(atoms.danger)),
    ] {
        if let Some(tok) = t.palette.tokens.get_mut(name) {
            tok.value = value;
        }
    }
    t
}

fn color_to_hex(c: Color) -> String {
    let r = (c.r * 255.0).round().clamp(0.0, 255.0) as u8;
    let g = (c.g * 255.0).round().clamp(0.0, 255.0) as u8;
    let b = (c.b * 255.0).round().clamp(0.0, 255.0) as u8;
    format!("#{r:02x}{g:02x}{b:02x}")
}
