[package]
name = "sola-bus"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sola-bus"
path = "src/main.rs"

[dependencies]
sola-core = { path = "../sola-core" }
tracing = "0.1"
postcard = { version = "1", features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
toml = { workspace = true }
uuid = { version = "1", features = ["v7", "serde"] }

[dev-dependencies]
tempfile = "3"
