[package]
name = "sola-bus"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sola-bus"
path = "src/main.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
postcard = { version = "1", features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v7", "serde"] }
