//! CEF callback handler implementations. Each handler trait that the
//! binding crate exposes gets implemented here and wired in
//! `browser::KitClient`. Handlers run on CEF's UI thread (= our main
//! thread), so dispatch to surface methods is direct.

// The `wrap_render_handler!`, `wrap_client!`, `wrap_life_span_handler!`,
// `wrap_request_handler!` macros expand to code that references trait names
// (`RenderHandler`, `Client`, `LifeSpanHandler`, `RequestHandler`, plus their
// `Wrap*` / `Impl*` companions, `RcImpl`, etc.) by bare names. They must be
// in scope via wildcard imports from the cef crate. This mirrors the macro's
// own docstring example (`# use cef::{*, rc::*};`).
#[allow(unused_imports)]
use cef::{rc::*, *};
// `on_before_close`, `on_render_process_terminated`, `on_process_message_received`
// etc. live on this trait, not directly on `BrowserSideRouter`.
use cef::wrapper::message_router::MessageRouterBrowserSideHandlerCallbacks;

use std::rc::Rc;

use crate::wayland::Surface;

// DRM fourcc constants (raw u32, little-endian "ASCII tag" interpretation).
// Sola handles the two CEF native OSR pixel layouts:
//   CEF RGBA_8888 — bytes in memory: R, G, B, A   → DRM_FORMAT_ABGR8888 (0x34324241 = b"AB24" LE)
//   CEF BGRA_8888 — bytes in memory: B, G, R, A   → DRM_FORMAT_ARGB8888 (0x34325241 = b"AR24" LE)
const DRM_FORMAT_ABGR8888: u32 = 0x34324241; // b"AB24"
const DRM_FORMAT_ARGB8888: u32 = 0x34325241; // b"AR24"

/// Map a CEF `ColorType` to the matching DRM fourcc pixel format constant.
///
/// CEF uses `cef::ColorType` (a newtype over `cef_color_type_t`) to
/// describe the per-pixel layout emitted by the GPU for OSR. The two
/// values CEF actually emits on Linux are:
///
///   - `RGBA_8888` — R, G, B, A byte order in memory → `DRM_FORMAT_ABGR8888`
///   - `BGRA_8888` — B, G, R, A byte order in memory → `DRM_FORMAT_ARGB8888`
///
/// (DRM fourcc names reflect the byte layout as a little-endian 32-bit
/// word, so "ABGR" means A is in the high byte, i.e. A-B-G-R from MSB to
/// LSB, which equals R-G-B-A from LSB to MSB — matching Skia's RGBA_8888.)
fn cef_format_to_drm(fmt: cef::ColorType) -> u32 {
    match fmt {
        cef::ColorType::RGBA_8888 => DRM_FORMAT_ABGR8888,
        cef::ColorType::BGRA_8888 => DRM_FORMAT_ARGB8888,
        // CEF OSR currently only emits ARGB/ABGR on Linux; default to ARGB.
        _ => DRM_FORMAT_ARGB8888,
    }
}

// CEF RenderHandler implementation. Receives accelerated paint callbacks
// on the UI thread and forwards the dma-buf fd + metadata to the bound
// Wayland surface via `Surface::present_dmabuf`.
//
// Generated by `wrap_render_handler!` which synthesises:
//   - the struct body (fields + hidden `cef_object` pointer)
//   - `KitRenderHandler::new(surface) -> cef::RenderHandler`
//   - `Clone` / `cef::rc::Rc` / `WrapRenderHandler` / `ImplRenderHandler` impls
cef::wrap_render_handler! {
    pub struct KitRenderHandler {
        pub surface: Rc<Surface>,
    }

    impl RenderHandler {
        fn view_rect(
            &self,
            _browser: Option<&mut cef::Browser>,
            rect: Option<&mut cef::Rect>,
        ) {
            let (w, h) = self.surface.size();
            if let Some(r) = rect {
                r.x = 0;
                r.y = 0;
                r.width = w;
                r.height = h;
            }
        }

        // Returning the view-shaped rect here (and from `screen_info`) and
        // a passthrough `screen_point` keeps CEF from auto-querying the
        // Wayland output for screen geometry. Without these, Chromium
        // sometimes picks up the compositor's preferred fractional scale
        // and applies it to OSR rasterisation — leading to "everything
        // gets smaller" drift after a resize or focus change. Pinning
        // these to scale = 1 with a (0,0,w,h) rect gives the renderer a
        // stable, deterministic answer and matches what `view_rect`
        // already reports.
        fn root_screen_rect(
            &self,
            _browser: Option<&mut cef::Browser>,
            rect: Option<&mut cef::Rect>,
        ) -> ::std::os::raw::c_int {
            let (w, h) = self.surface.size();
            if let Some(r) = rect {
                r.x = 0;
                r.y = 0;
                r.width = w;
                r.height = h;
            }
            1
        }

        fn screen_point(
            &self,
            _browser: Option<&mut cef::Browser>,
            view_x: ::std::os::raw::c_int,
            view_y: ::std::os::raw::c_int,
            screen_x: Option<&mut ::std::os::raw::c_int>,
            screen_y: Option<&mut ::std::os::raw::c_int>,
        ) -> ::std::os::raw::c_int {
            // We don't do multi-monitor here; the surface is the screen.
            if let Some(sx) = screen_x { *sx = view_x; }
            if let Some(sy) = screen_y { *sy = view_y; }
            1
        }

        fn screen_info(
            &self,
            _browser: Option<&mut cef::Browser>,
            screen_info: Option<&mut cef::ScreenInfo>,
        ) -> ::std::os::raw::c_int {
            let (w, h) = self.surface.size();
            if let Some(si) = screen_info {
                si.device_scale_factor = 1.0;
                si.depth = 24;
                si.depth_per_component = 8;
                si.is_monochrome = 0;
                si.rect = cef::Rect { x: 0, y: 0, width: w, height: h };
                si.available_rect = cef::Rect { x: 0, y: 0, width: w, height: h };
            }
            1
        }

        fn on_accelerated_paint(
            &self,
            _browser: Option<&mut cef::Browser>,
            _type_: cef::PaintElementType,
            dirty_rects: Option<&[cef::Rect]>,
            info: Option<&cef::AcceleratedPaintInfo>,
        ) {
            let info = match info {
                Some(i) => i,
                None => return,
            };
            // Chromium OSR always produces a single-plane ARGB/ABGR dma-buf.
            if info.plane_count < 1 {
                return;
            }
            let plane = &info.planes[0];

            let damage: Vec<(i32, i32, i32, i32)> = dirty_rects
                .map(|rects| rects.iter().map(|r| (r.x, r.y, r.width, r.height)).collect())
                .unwrap_or_default();

            // Use the dma-buf's *actual* rasterised dimensions, not the
            // surface's logical size. During a resize the surface state
            // updates immediately on `configure`, but CEF's GPU process
            // may still be emitting frames sized to the previous
            // `view_rect`. Telling the compositor `wl_buffer.width =
            // surface.size()` while the buffer was actually rasterised
            // at the previous size produces stride mismatches and
            // sticky/stale frames. `extra.coded_size` is the buffer's
            // own dimensions as the GPU produced it.
            let coded = &info.extra.coded_size;
            let (w, h) = (coded.width, coded.height);

            // SAFETY: `plane.fd` is a valid open dma-buf file descriptor for
            // the duration of this callback. CEF retains ownership; the
            // compositor takes a Wayland-protocol reference via `wl_buffer`.
            self.surface.present_dmabuf(
                plane.fd,
                cef_format_to_drm(info.format),
                info.modifier,
                plane.stride,
                plane.offset as u32,
                w,
                h,
                &damage,
            );
        }

        // CPU OSR path. Fires when the browser was created with
        // `shared_texture_enabled = 0` — CEF rasterises to GPU memory,
        // reads back to a CPU `BGRA8888` buffer, and hands us a pointer
        // valid only for the duration of this call. Surface::present_paint
        // memcpys into a wl_shm slot and attaches the resulting wl_buffer.
        fn on_paint(
            &self,
            _browser: Option<&mut cef::Browser>,
            _type_: cef::PaintElementType,
            dirty_rects: Option<&[cef::Rect]>,
            buffer: *const u8,
            width: ::std::os::raw::c_int,
            height: ::std::os::raw::c_int,
        ) {
            let damage: Vec<(i32, i32, i32, i32)> = dirty_rects
                .map(|rects| rects.iter().map(|r| (r.x, r.y, r.width, r.height)).collect())
                .unwrap_or_default();
            self.surface.present_paint(buffer, width, height, &damage);
        }
    }
}

// CEF Client implementation. Exposes `KitRenderHandler` for OSR plus the
// MessageRouter wiring (`on_process_message_received` + LifeSpan +
// Request handlers) that bridges JS `cefQuery` to Rust. All other handler
// slots return `None` (the `ImplClient` defaults).
cef::wrap_client! {
    pub struct KitClient {
        pub render_handler: cef::RenderHandler,
        pub life_span_handler: cef::LifeSpanHandler,
        pub request_handler: cef::RequestHandler,
        pub display_handler: cef::DisplayHandler,
    }

    impl Client {
        fn render_handler(&self) -> Option<cef::RenderHandler> {
            Some(self.render_handler.clone())
        }

        fn life_span_handler(&self) -> Option<cef::LifeSpanHandler> {
            Some(self.life_span_handler.clone())
        }

        fn request_handler(&self) -> Option<cef::RequestHandler> {
            Some(self.request_handler.clone())
        }

        fn display_handler(&self) -> Option<cef::DisplayHandler> {
            Some(self.display_handler.clone())
        }

        fn on_process_message_received(
            &self,
            browser: Option<&mut cef::Browser>,
            frame: Option<&mut cef::Frame>,
            source_process: cef::ProcessId,
            message: Option<&mut cef::ProcessMessage>,
        ) -> ::std::os::raw::c_int {
            let handled = crate::cef::router::browser_router()
                .on_process_message_received(
                    browser.cloned(),
                    frame.cloned(),
                    source_process,
                    message.cloned(),
                );
            if handled { 1 } else { 0 }
        }
    }
}

// DisplayHandler — routes the renderer's `console.log/warn/error`
// output into our tracing pipeline (with Chromium's own log severity
// set to DISABLE in init.rs, JS console messages would otherwise be
// dropped) and translates CSS cursor changes into Wayland cursor-
// shape requests via the channel in `wayland::cursor`.
cef::wrap_display_handler! {
    pub struct KitDisplayHandler {}

    impl DisplayHandler {
        // CSS `cursor:` changes inside the webview surface as
        // on_cursor_change. CEF runs this on the UI thread = our main
        // thread, so writing to the thread-local pending slot in
        // `wayland::cursor` is lock-free; the next Wayland dispatch
        // tick drains it and issues the wp_cursor_shape_v1 set_shape.
        // Custom cursors and "no cursor" (CT_NONE) are intentionally
        // unsupported — see wayland::cursor::cef_to_shape.
        fn on_cursor_change(
            &self,
            _browser: Option<&mut cef::Browser>,
            _cursor: ::std::os::raw::c_ulong,
            type_: cef::CursorType,
            _custom_cursor_info: Option<&cef::CursorInfo>,
        ) -> ::std::os::raw::c_int {
            if let Some(shape) = crate::wayland::cursor::cef_to_shape(type_) {
                crate::wayland::cursor::set_pending(shape);
                1
            } else {
                // Unmapped type (CT_NONE, CT_CUSTOM, CT_DND_*, …).
                // Returning 0 signals "not handled"; CEF has no
                // default behavior for OSR cursors so the cursor
                // simply stays on whatever shape it last had.
                0
            }
        }

        fn on_console_message(
            &self,
            _browser: Option<&mut cef::Browser>,
            level: cef::LogSeverity,
            message: Option<&cef::CefString>,
            source: Option<&cef::CefString>,
            line: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int {
            // CefString implements Display via its UTF-16 → UTF-8
            // conversion; format!() pulls a clean Rust String out.
            let msg = message.map(|s| s.to_string()).unwrap_or_default();
            // Strip a single trailing newline if Chromium added one — keeps
            // the log file's one-line-per-event invariant.
            let msg = msg.strip_suffix('\n').unwrap_or(&msg);
            let src = source.map(|s| s.to_string()).unwrap_or_default();

            // LogSeverity → tracing level. DEFAULT and INFO both map to
            // info; VERBOSE is debug (we don't surface trace by default
            // because console.debug is common enough that trace would be
            // too quiet); WARNING/ERROR/FATAL escalate as expected.
            match level {
                cef::LogSeverity::VERBOSE => {
                    tracing::debug!(target: "sola_kit::console", source = %src, line, "{msg}");
                }
                cef::LogSeverity::WARNING => {
                    tracing::warn!(target: "sola_kit::console", source = %src, line, "{msg}");
                }
                cef::LogSeverity::ERROR | cef::LogSeverity::FATAL => {
                    tracing::error!(target: "sola_kit::console", source = %src, line, "{msg}");
                }
                _ => {
                    // DEFAULT / INFO / anything Chromium adds later.
                    tracing::info!(target: "sola_kit::console", source = %src, line, "{msg}");
                }
            }

            // Return 1 ("handled") so CEF's internal logger doesn't also
            // emit the message — we've already routed it.
            1
        }
    }
}

// LifeSpanHandler — needed only to forward `on_before_close` to the
// MessageRouter so it can cancel pending queries for this browser.
cef::wrap_life_span_handler! {
    pub struct KitLifeSpanHandler {}

    impl LifeSpanHandler {
        fn on_before_close(&self, browser: Option<&mut cef::Browser>) {
            if let Some(b) = browser.as_ref() {
                crate::cef::router::unregister_window(b.identifier());
            }
            crate::cef::router::browser_router().on_before_close(browser.cloned());
        }
    }
}

// RequestHandler — forwards renderer-process termination + cross-frame
// navigation to the MessageRouter so it can cancel + re-issue pending
// queries appropriately.
cef::wrap_request_handler! {
    pub struct KitRequestHandler {}

    impl RequestHandler {
        fn on_render_process_terminated(
            &self,
            browser: Option<&mut cef::Browser>,
            _status: cef::TerminationStatus,
            _error_code: ::std::os::raw::c_int,
            _error_string: Option<&cef::CefString>,
        ) {
            crate::cef::router::browser_router()
                .on_render_process_terminated(browser.cloned());
        }
    }
}
