//! Raw FFI bindings generated by bindgen at build time from
//! `src/wpe_wrapper.h`. Output lives in `$OUT_DIR/wpe_bindings.rs`.
//!
//! Every consumer (`crate::wpe`, binaries, etc.) imports symbols
//! from here so we never have multiple copies of the generated
//! types floating around.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/wpe_bindings.rs"));
