[package]
name = "sola-make"
version.workspace = true
edition.workspace = true

[dependencies]
bzip2 = "0.4"
clap = { version = "4", features = ["derive"] }
dirs = "5"
notify = "8"
serde = { version = "1", features = ["derive"] }
tar = "0.4"
toml = "0.8"
ureq = { version = "2", features = ["tls"] }
