//! Raw FFI bindings generated by bindgen at build time from
//! `src/wpe/wpe_wrapper.h`. Output lives in `$OUT_DIR/wpe_bindings.rs`.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/wpe_bindings.rs"));
