//! CEF callback handler implementations. Each handler trait that the
//! binding crate exposes gets implemented here and wired in
//! `browser::KitClient`. Handlers run on CEF's UI thread (= our main
//! thread), so dispatch to surface methods is direct.

// The `wrap_render_handler!` and `wrap_client!` macros expand to code that
// references `RenderHandler`, `Client`, `WrapRenderHandler`, `ImplRenderHandler`,
// `WrapClient`, `ImplClient`, `RcImpl`, etc. by bare names. They must be in
// scope via wildcard imports from the cef crate. This mirrors the macro's own
// docstring example (`# use cef::{*, rc::*};`).
#[allow(unused_imports)]
use cef::{rc::*, *};

use std::rc::Rc;

use crate::wayland::Surface;

// DRM fourcc constants (raw u32, little-endian "ASCII tag" interpretation).
// Sola handles the two CEF native OSR pixel layouts:
//   CEF RGBA_8888 — bytes in memory: R, G, B, A   → DRM_FORMAT_ABGR8888 (0x34324241 = b"AB24" LE)
//   CEF BGRA_8888 — bytes in memory: B, G, R, A   → DRM_FORMAT_ARGB8888 (0x34325241 = b"AR24" LE)
const DRM_FORMAT_ABGR8888: u32 = 0x34324241; // b"AB24"
const DRM_FORMAT_ARGB8888: u32 = 0x34325241; // b"AR24"

/// Map a CEF `ColorType` to the matching DRM fourcc pixel format constant.
///
/// CEF uses `cef::ColorType` (a newtype over `cef_color_type_t`) to
/// describe the per-pixel layout emitted by the GPU for OSR. The two
/// values CEF actually emits on Linux are:
///
///   - `RGBA_8888` — R, G, B, A byte order in memory → `DRM_FORMAT_ABGR8888`
///   - `BGRA_8888` — B, G, R, A byte order in memory → `DRM_FORMAT_ARGB8888`
///
/// (DRM fourcc names reflect the byte layout as a little-endian 32-bit
/// word, so "ABGR" means A is in the high byte, i.e. A-B-G-R from MSB to
/// LSB, which equals R-G-B-A from LSB to MSB — matching Skia's RGBA_8888.)
fn cef_format_to_drm(fmt: cef::ColorType) -> u32 {
    match fmt {
        cef::ColorType::RGBA_8888 => DRM_FORMAT_ABGR8888,
        cef::ColorType::BGRA_8888 => DRM_FORMAT_ARGB8888,
        // CEF OSR currently only emits ARGB/ABGR on Linux; default to ARGB.
        _ => DRM_FORMAT_ARGB8888,
    }
}

// CEF RenderHandler implementation. Receives accelerated paint callbacks
// on the UI thread and forwards the dma-buf fd + metadata to the bound
// Wayland surface via `Surface::present_dmabuf`.
//
// Generated by `wrap_render_handler!` which synthesises:
//   - the struct body (fields + hidden `cef_object` pointer)
//   - `KitRenderHandler::new(surface) -> cef::RenderHandler`
//   - `Clone` / `cef::rc::Rc` / `WrapRenderHandler` / `ImplRenderHandler` impls
cef::wrap_render_handler! {
    pub struct KitRenderHandler {
        pub surface: Rc<Surface>,
    }

    impl RenderHandler {
        fn view_rect(
            &self,
            _browser: Option<&mut cef::Browser>,
            rect: Option<&mut cef::Rect>,
        ) {
            let (w, h) = self.surface.size();
            if let Some(r) = rect {
                r.x = 0;
                r.y = 0;
                r.width = w;
                r.height = h;
            }
        }

        fn on_accelerated_paint(
            &self,
            _browser: Option<&mut cef::Browser>,
            _type_: cef::PaintElementType,
            dirty_rects: Option<&[cef::Rect]>,
            info: Option<&cef::AcceleratedPaintInfo>,
        ) {
            tracing::info!(
                has_info = info.is_some(),
                dirty_rects = dirty_rects.map(|r| r.len()).unwrap_or(0),
                "on_accelerated_paint fired"
            );
            let info = match info {
                Some(i) => i,
                None => return,
            };
            tracing::info!(
                plane_count = info.plane_count,
                modifier = info.modifier,
                fd = info.planes[0].fd,
                stride = info.planes[0].stride,
                "on_accelerated_paint: dma-buf info"
            );
            // Chromium OSR always produces a single-plane ARGB/ABGR dma-buf.
            if info.plane_count < 1 {
                return;
            }
            let plane = &info.planes[0];

            let damage: Vec<(i32, i32, i32, i32)> = dirty_rects
                .map(|rects| rects.iter().map(|r| (r.x, r.y, r.width, r.height)).collect())
                .unwrap_or_default();

            let (w, h) = self.surface.size();

            // SAFETY: `plane.fd` is a valid open dma-buf file descriptor for
            // the duration of this callback. CEF retains ownership; the
            // compositor takes a Wayland-protocol reference via `wl_buffer`.
            self.surface.present_dmabuf(
                plane.fd,
                cef_format_to_drm(info.format),
                info.modifier,
                plane.stride,
                plane.offset as u32,
                w,
                h,
                &damage,
            );
        }

        // CPU OSR path. Fires when the browser was created with
        // `shared_texture_enabled = 0` — CEF rasterises to GPU memory,
        // reads back to a CPU `BGRA8888` buffer, and hands us a pointer
        // valid only for the duration of this call. Surface::present_paint
        // memcpys into a wl_shm slot and attaches the resulting wl_buffer.
        fn on_paint(
            &self,
            _browser: Option<&mut cef::Browser>,
            _type_: cef::PaintElementType,
            dirty_rects: Option<&[cef::Rect]>,
            buffer: *const u8,
            width: ::std::os::raw::c_int,
            height: ::std::os::raw::c_int,
        ) {
            tracing::info!(
                width,
                height,
                dirty_rects = dirty_rects.map(|r| r.len()).unwrap_or(0),
                "on_paint fired"
            );
            let damage: Vec<(i32, i32, i32, i32)> = dirty_rects
                .map(|rects| rects.iter().map(|r| (r.x, r.y, r.width, r.height)).collect())
                .unwrap_or_default();
            self.surface.present_paint(buffer, width, height, &damage);
        }
    }
}

// CEF Client implementation. Exposes `KitRenderHandler` for OSR; all
// other handler slots return `None` (the `ImplClient` defaults).
//
// Generated by `wrap_client!` which synthesises:
//   - the struct body (fields + hidden `cef_object` pointer)
//   - `KitClient::new(render_handler) -> cef::Client`
//   - `Clone` / `cef::rc::Rc` / `WrapClient` / `ImplClient` impls
cef::wrap_client! {
    pub struct KitClient {
        pub render_handler: cef::RenderHandler,
    }

    impl Client {
        fn render_handler(&self) -> Option<cef::RenderHandler> {
            Some(self.render_handler.clone())
        }
    }
}
