//! CEF process startup. Two distinct entry points:
//!
//! - `short_circuit_if_subprocess()` — called at the very top of `main()`.
//!   If we were re-execed by CEF as a renderer/GPU/utility worker, this
//!   hands control to `CefExecuteProcess` and exits the process when
//!   that worker is done.
//! - `initialize()` — called once in the browser process to start CEF.

use std::process::ExitCode;

/// Subprocess gate — call this at the top of `main()`.
///
/// Returns `Some(ExitCode)` if the current process is a CEF worker
/// (renderer/GPU/utility/zygote); the caller should `return code` from
/// `main()` immediately. Returns `None` if this is the main browser
/// process.
pub fn short_circuit_if_subprocess() -> Option<ExitCode> {
    // `Args::new()` reads `std::env::args()` internally and holds the
    // CString/argv storage alive for the duration of this call.
    let args = cef::args::Args::new();
    let main_args = args.as_main_args();

    // Linux: no Windows sandbox — pass null.
    // Returns >= 0 if this process is a CEF worker (renderer/GPU/utility/zygote);
    // returns -1 if this is the main browser process.
    let result = cef::execute_process(Some(main_args), None, std::ptr::null_mut());

    if result >= 0 {
        // CEF docs: the return value is the worker's exit code.
        // Clamp to u8 range — process exit codes are 0–255 on POSIX.
        Some(ExitCode::from(result.clamp(0, 255) as u8))
    } else {
        // result == -1: we are the main browser process, continue normally.
        None
    }
}

/// Initialize CEF in the browser process. Call exactly once, after
/// `short_circuit_if_subprocess` has returned None.
pub fn initialize() {
    let release   = crate::cef::distribution::release_dir();
    let resources = crate::cef::distribution::resources_dir();
    let locales   = crate::cef::distribution::locales_dir();
    let exe = std::env::current_exe().expect("current_exe");

    let mut settings = cef::Settings::default();
    settings.framework_dir_path    = cef::CefString::from(&*release.to_string_lossy());
    settings.resources_dir_path    = cef::CefString::from(&*resources.to_string_lossy());
    settings.locales_dir_path      = cef::CefString::from(&*locales.to_string_lossy());
    settings.browser_subprocess_path = cef::CefString::from(&*exe.to_string_lossy());
    settings.no_sandbox                  = 1; // true — no Windows sandbox on Linux
    settings.windowless_rendering_enabled = 1; // true — OSR / off-screen rendering
    settings.external_message_pump       = 0; // false — use cef::run_message_loop
    settings.multi_threaded_message_loop = 0; // false — single main-thread loop
    settings.log_severity = cef::LogSeverity::WARNING;

    // `Args::new()` reads `std::env::args()` internally and keeps the
    // CString/argv storage alive for the duration of the call.
    let args = cef::args::Args::new();
    let main_args = args.as_main_args();

    // CEF C-API convention: returns 1 (non-zero positive) on success, 0 on failure.
    let rc = cef::initialize(Some(main_args), Some(&settings), None, std::ptr::null_mut());
    if rc <= 0 {
        panic!("cef::initialize failed (return code {rc})");
    }
}

/// Register the `app://` custom scheme factory. Call once, immediately
/// after `initialize()` succeeds.
///
/// CEF's URL parser must know about `app://` as a standard-format scheme
/// (i.e. one with a host component) for host-stripping to work. For now
/// we rely on CEF treating unregistered schemes as opaque — the scheme
/// factory still fires, and our factory ignores the authority component.
/// If `app://` needs proper origin-isolation treatment in a future task,
/// add an `App` impl with `on_register_custom_schemes` (called before
/// `cef::initialize`) to declare it as a standard scheme.
pub fn register_app_scheme() {
    let scheme = cef::CefString::from("app");
    // Empty domain = match all authorities under app://.
    let domain = cef::CefString::from("");
    // `AppSchemeFactory::new()` is generated by `wrap_scheme_handler_factory!`
    // and returns a `cef::SchemeHandlerFactory`.
    let mut factory = crate::cef::scheme::AppSchemeFactory::new();
    cef::register_scheme_handler_factory(Some(&scheme), Some(&domain), Some(&mut factory));
}

/// Run CEF's message loop on the current (main) thread. Blocks until
/// `cef::quit_message_loop()` is posted from any CEF thread.
pub fn run_message_loop() {
    cef::run_message_loop();
}

/// Tear down CEF cleanly. Call once after `run_message_loop` returns.
pub fn shutdown() {
    cef::shutdown();
}
